# Crane-based derivation for the sonify-health-server binary, with
# the compiled Elm frontend assets bundled under
# share/sonify-health/frontend.  The server is the daemon binary
# that serves the web UI, so the frontend lives here rather than
# with the cli.
#
# Called from flake.nix (via mkRustProject's per-crate override
# convention) with: import ./server.nix { inherit craneLib commonArgs pkgs; }
#
# The package output includes:
#   $out/bin/sonify-health-server              — the daemon binary
#   $out/share/sonify-health/frontend/         — compiled Elm assets
#
# The NixOS/Darwin modules pass --frontend-path pointing at the share
# directory.
#
# Elm build: uses pkgs.elmPackages.fetchElmDeps with the elm-srcs.nix
# and registry.dat files generated by elm2nix.  All package fetching
# happens through individual fixed-output derivations, so the build is
# fully offline and hermetic.
#
# When elm.json dependency versions change, regenerate both files:
#   cd frontend
#   nix run 'github:NixOS/nixpkgs/25.11#elm2nix' -- convert 2>/dev/null > elm-srcs.nix
#   nix run 'github:NixOS/nixpkgs/25.11#elm2nix' -- snapshot
# then commit elm-srcs.nix and registry.dat.
{
  craneLib,
  commonArgs,
  pkgs,
}: let
  elmFrontend = pkgs.stdenv.mkDerivation {
    name = "sonify-health-elm-frontend";
    src = ../../frontend;
    # The Elm compiler that builds the dashboard's elm.js bundle.
    nativeBuildInputs = [pkgs.elmPackages.elm];

    configurePhase = pkgs.elmPackages.fetchElmDeps {
      elmPackages = import ../../frontend/elm-srcs.nix;
      elmVersion = "0.19.1";
      registryDat = ../../frontend/registry.dat;
    };

    buildPhase = ''
      elm make src/Main.elm --optimize --output elm.js
    '';

    installPhase = ''
      mkdir -p $out
      cp elm.js $out/
      cp public/style.css $out/
      # Stamp the script src with the Nix store hash so each build gets a
      # unique URL.  Browsers that cached /elm.js from a previous build will
      # fetch the new /elm.js?v=<hash> URL instead.
      STORE_HASH=$(basename $out | cut -d'-' -f1)
      sed "s|/elm.js|/elm.js?v=$STORE_HASH|g" public/index.html > $out/index.html
    '';
  };

  binary = craneLib.buildPackage (commonArgs
    // {
      pname = "sonify-health-server";
      cargoExtraArgs = "--package sonify-health-server";
    });
in
  pkgs.symlinkJoin {
    name = "sonify-health-server";
    paths = [binary];
    postBuild = ''
      mkdir --parents $out/share/sonify-health
      ln --symbolic ${elmFrontend} $out/share/sonify-health/frontend
    '';
  }
