# Crane-based derivation for the sonify-health-server binary.
#
# Called from flake.nix (via mkRustPackages' per-crate override
# convention) with: import ./server.nix { inherit craneLib commonArgs pkgs; }
# The same override serves the native, musl, gnu, and darwin-cross builds,
# since each of those helpers delegates to mkRustPackages, so every release
# variant embeds the frontend the same way.
#
# The package output is a single self-contained binary:
#   $out/bin/sonify-health-server — the daemon, with the compiled Elm
#                                   dashboard embedded into it.
#
# The frontend is built by the `elmFrontend` derivation below and handed to
# the crate build through the SONIFY_HEALTH_FRONTEND_DIR environment
# variable, which the server crate's build.rs forwards to the `rust_embed`
# `Frontend` type.  Embedding (rather than shipping a sibling asset
# directory) means a downloaded release binary needs nothing alongside it —
# there is no --frontend-path to point at a separate directory.
#
# Elm build: uses pkgs.elmPackages.fetchElmDeps with the elm-srcs.nix
# and registry.dat files generated by elm2nix.  All package fetching
# happens through individual fixed-output derivations, so the build is
# fully offline and hermetic.
#
# When elm.json dependency versions change, regenerate both files:
#   cd frontend
#   nix run 'github:NixOS/nixpkgs/25.11#elm2nix' -- convert 2>/dev/null > elm-srcs.nix
#   nix run 'github:NixOS/nixpkgs/25.11#elm2nix' -- snapshot
# then commit elm-srcs.nix and registry.dat.
{
  craneLib,
  commonArgs,
  pkgs,
}: let
  elmFrontend = pkgs.stdenv.mkDerivation {
    name = "sonify-health-elm-frontend";
    src = ../../frontend;
    # The Elm compiler that builds the dashboard's elm.js bundle.
    nativeBuildInputs = [pkgs.elmPackages.elm];

    configurePhase = pkgs.elmPackages.fetchElmDeps {
      elmPackages = import ../../frontend/elm-srcs.nix;
      elmVersion = "0.19.1";
      registryDat = ../../frontend/registry.dat;
    };

    buildPhase = ''
      elm make src/Main.elm --optimize --output elm.js
    '';

    installPhase = ''
      mkdir -p $out
      cp elm.js $out/
      cp public/style.css $out/
      # Stamp the script src with the Nix store hash so each build gets a
      # unique URL.  Browsers that cached /elm.js from a previous build will
      # fetch the new /elm.js?v=<hash> URL instead.
      STORE_HASH=$(basename $out | cut -d'-' -f1)
      sed "s|/elm.js|/elm.js?v=$STORE_HASH|g" public/index.html > $out/index.html
    '';
  };
in
  craneLib.buildPackage (commonArgs
    // {
      pname = "sonify-health-server";
      cargoExtraArgs = "--package sonify-health-server";
      # The server crate's build.rs reads this and forwards it to the
      # `rust_embed` `Frontend` type, which bakes the assets into the binary.
      # Referencing the derivation here also makes it a build dependency, so
      # the Elm bundle is compiled before the crate build runs.
      SONIFY_HEALTH_FRONTEND_DIR = "${elmFrontend}";
    })
